# Generated by Django 5.2.3 on 2025-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_colorblindtest_erg_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorblindtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='colorblindtest',
            name='result_type',
            field=models.CharField(max_length=100),
        ),
    ]
